# XXX: created_at, updated_at and happened_at need to be defined as date fields of specific format
# XXX: can url types be defined and enforced?
#
# Looks like data types can be defined: https://swagger.io/docs/specification/data-models/data-types/

# XXX: If no authorization is provided, we get a 302 redirect. I'm not sure how to handle this in OpenAPI

# NOTE: Swagger docs (https://swagger.io/docs/specification/describing-responses/) says "that, currently, OpenAPI
# Specification does not permit to define common response headers for different response codes or different API
# operations. You need to define the headers for each response individually."
#
# Copy-pasta sucks!

openapi: 3.0.1

info:
  title: Monica CRM API
  description: |-
    Monica helps you organize the social interactions with your loved ones.

    This document describes how to use Monica's API. This document is heavily inspired by
    [GitHub's](https://developer.github.com/v3) and [Stripe's](https://stripe.com/docs/api) API. Please use the API in
    a nice way and don't be a jerk.
  termsOfService: https://www.monicahq.com/terms
  license:
    name: GNU Affero General Public License
    url: https://www.gnu.org/licenses/agpl-3.0.txt
  version: "0.1"

servers:
- url: /api
  description: Point to the api point for the server being accessed.
- url: https://virtserver.swaggerhub.com/harleypig/MonicaCRM-API/0.1
  description: SwaggerHub API Auto Mocking

security:
  - bearerAuth: []

# The order defined here is how the various groups will be displayed in the swagger generated document.
tags:
#  name: Activities
#  description: |-
#    The Activity object represents activities made with one or more contacts. Use it to keep track of what you've done.
#    An activity can't be orphan - it needs to be linked to at least one contact.
#  externalDocs:
#    description: Documentation for Activities
#    url: 'https://www.monicahq.com/api/activities'

#  - name: Activity types
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Activity types
#      url: 'https://www.monicahq.com/api/...'

  - name: Activity Type Categories
    description: |-
      When adding an activity done with a contact, you can associate it with a
      type of activity. This is useful to categorize your activities done with your
      contacts.

      An activity type belongs to an activity type categories.
    externalDocs:
      description:  Documentation for Activity type categories
      url: 'https://www.monicahq.com/api/activitytypecategories'

#  - name: Addresses
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Addresses
#      url: 'https://www.monicahq.com/api/...'

#  - name: Audit logs
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Audit logs
#      url: 'https://www.monicahq.com/api/...'

#  - name: Calls
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Calls
#      url: 'https://www.monicahq.com/api/...'

#  - name: Companies
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Companies
#      url: 'https://www.monicahq.com/api/...'

#  - name: Compliance
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Compliance
#      url: 'https://www.monicahq.com/api/...'

#  - name: Contacts
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Contacts
#      url: 'https://www.monicahq.com/api/...'

#  - name: Contact Fields
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Contact Fields
#      url: 'https://www.monicahq.com/api/...'

#  - name: Contact Field Types
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Contact Field Types
#      url: 'https://www.monicahq.com/api/...'

#  - name: Conversations
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Conversations
#      url: 'https://www.monicahq.com/api/...'

#  - name: Countries
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Countries
#      url: 'https://www.monicahq.com/api/...'

#  - name: Currencies
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Currencies
#      url: 'https://www.monicahq.com/api/...'

#  - name: Debts
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Debts
#      url: 'https://www.monicahq.com/api/...'

#  - name: Documents
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Documents
#      url: 'https://www.monicahq.com/api/...'

#  - name: Genders
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Genders
#      url: 'https://www.monicahq.com/api/...'

#  - name: Gifts
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Gifts
#      url: 'https://www.monicahq.com/api/...'

#  - name: Groups
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Groups
#      url: 'https://www.monicahq.com/api/...'

#  - name: Journal entries
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Journal entries
#      url: 'https://www.monicahq.com/api/...'

#  - name: Notes
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Notes
#      url: 'https://www.monicahq.com/api/...'

#  - name: Occupations
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Occupations
#      url: 'https://www.monicahq.com/api/...'

#  - name: Photos
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Photos
#      url: 'https://www.monicahq.com/api/...'

#  - name: Relationships
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Relationships
#      url: 'https://www.monicahq.com/api/...'

#  - name: Relationship Types
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Relationship Types
#      url: 'https://www.monicahq.com/api/...'

#  - name: Relationship Type Groups
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Relationship Type Groups
#      url: 'https://www.monicahq.com/api/...'

#  - name: Reminders
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Reminders
#      url: 'https://www.monicahq.com/api/...'

#  - name: Tags
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Tags
#      url: 'https://www.monicahq.com/api/...'

#  - name: Tasks
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for Tasks
#      url: 'https://www.monicahq.com/api/...'

#  - name: User
#    description: 'description goes here'
#    externalDocs:
#      description:  Documentation for User
#      url: 'https://www.monicahq.com/api/...'

#############################################################################
paths:
  /activitytypecategories:

    #------------------------------------------------------------------------
    get:
      tags:
      - Activity Type Categories
      description: Get existing categories.
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
      responses:
        "200":
          description: Ok
          headers:
            X-RateLimit-Limit:
              description: Number of requests allowed per hour
              required: true
              style: simple
              explode: false
              schema:
                minimum: 0
                type: integer
            X-RateLimit-Remaining:
              description: Number of requests remaining
              required: true
              style: simple
              explode: false
              schema:
                minimum: 0
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response_body_ActivityTypeCategories_array'
              examples:
                Response Body:
                  $ref: '#/components/examples/response_body_ActivityTypeCategories_array_examples'

    #------------------------------------------------------------------------
    post:
      tags:
      - Activity Type Categories
      description: Create an activity type category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request_body_ActivityTypeCategories'
            examples:
              Request Body:
                $ref: '#/components/examples/POST_ActivityTypeCategories_body_examples'
      responses:
        "200":
          description: Ok
          headers:
            X-RateLimit-Limit:
              description: Number of requests allowed per hour
              required: true
              style: simple
              explode: false
              schema:
                minimum: 0
                type: integer
            X-RateLimit-Remaining:
              description: Number of requests remaining
              required: true
              style: simple
              explode: false
              schema:
                minimum: 0
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OK_POST_PUT_ActivityTypeCategories'
              examples:
                Response Body:
                  $ref: '#/components/examples/response_body_ActivityTypeCategories_examples'

  ###########################################################################
  /activitytypecategories/{ActivityTypeCategoryID}:

    #------------------------------------------------------------------------
    get:
      tags:
      - Activity Type Categories
      description: Get activity type specified by ActivityTypeCategoryID
      parameters:
        - $ref: '#/components/parameters/activityTypeCategoryIDParameter'
      responses:
        "200":
          description: Response when request for ActivityTypeCategory is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response_body_ActivityTypeCategories'
              examples:
                Response  Body:
                  $ref: '#/components/examples/response_body_ActivityTypeCategories_examples'

    #------------------------------------------------------------------------
    put:
      tags:
      - Activity Type Categories
      description: Modify an activity type category specified by ActivityTypeCategoryID
      parameters:
        - $ref: '#/components/parameters/activityTypeCategoryIDParameter'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request_body_ActivityTypeCategories'
            examples:
              Request Body:
                $ref: '#/components/examples/PUT_ActivityTypeCategoriesID_examples'
      responses:
        "200":
          description: Response Body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OK_POST_PUT_ActivityTypeCategories'
              examples:
                Response Body:
                  $ref: '#/components/examples/response_body_ActivityTypeCategories_examples'

    #------------------------------------------------------------------------
    delete:
      tags:
      - Activity Type Categories
      description: Delete an activity type category specified by ActivityTypeCategoryID
      parameters:
        - $ref: '#/components/parameters/activityTypeCategoryIDParameter'
      responses:
        "200":
          description: Response Body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response_body_delete'
              examples:
                Response Body:
                  $ref: '#/components/examples/response_body_delete_examples'

#############################################################################
components:

#  #--------------------------------------------------------------------------
#  headers:

  #--------------------------------------------------------------------------
  parameters:
    page:
      name: page
      in: query
      description: "The page number being requested, defaults to 1"
      required: false
      style: form
      explode: true
      schema:
        minimum: 1
        type: integer
        default: 1
      example: 1

    limit:
      name: limit
      in: query
      description: "The number of entries per page, defaults to 10, maximum is 100"
      required: false
      style: form
      explode: true
      schema:
        maximum: 100
        minimum: 1
        type: integer
        default: 10
      example: 50

    activityTypeCategoryIDParameter:
      name: ActivityTypeCategoryID
      in: path
      description: ActivityTypeCategory ID
      required: true
      style: simple
      explode: false
      schema:
        minimum: 1
        type: integer
      example: 1

  #--------------------------------------------------------------------------
  schemas:
    idObject:
      type: object
      properties:
        id:
          minimum: 1
          type: integer

    # 2021-07-21T17:32:28Z
    dateTime:
      type: string
      format: date-time

    # 2021-07-21
    date:
      type: string
      format: date

    # Request body for POST and PUT
    request_body_ActivityTypeCategories:
      type: object
      properties:
        name:
          type: string

    # Response data for both GETs, POST and PUT
    response_data_ActivityTypeCategories:
      type: object
      properties:
        id:
          minimum: 1
          type: integer

        # XXX: Is this always going to be 'activityTypeCategory'?
        object:
          type: string

        name:
          type: string
        account:
          $ref: '#/components/schemas/idObject'
        updated_at:
          $ref: '#/components/schemas/dateTime'
        created_at:
          $ref: '#/components/schemas/dateTime'

    # Response body for plain get.
    response_body_ActivityTypeCategories_array:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/response_data_ActivityTypeCategories'
        meta:
          $ref: '#/components/schemas/meta'
        links:
          $ref: '#/components/schemas/links'

    # Response body for post, get|put{id}
    response_body_ActivityTypeCategories:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/response_data_ActivityTypeCategories'

    #------------------------------------------------------------------------
    # DELETE
    # All resources have a delete that returns this format.
    # XXX: Verify this!

    response_body_delete:
      type: object
      properties:
        deleted:
          type: boolean
        id:
          minimum: 1
          type: integer

  #--------------------------------------------------------------------------
  # Definitions for responses that have pagination.

    links:
      type: object
      properties:
        next:
          type: string
        last:
          type: string
        prev: {}
        first:
          type: string

    meta:
      type: object
      properties:
        # path is a full url
        path:
          type: string
        per_page:
          type: integer
        total:
          type: integer
        last_page:
          type: integer
        from:
          type: integer
        to:
          type: integer
        current_page:
          type: integer
        links:
          type: array
          items:
            $ref: '#/components/schemas/meta_links'

    meta_links:
      type: object
      properties:
        active:
          type: boolean
        label:
          type: string
        url: {}

  #--------------------------------------------------------------------------
  examples:

    #------------------------------------------------------------------------
    # GET /activitytypecategories/

    response_body_ActivityTypeCategories_array_examples:
        value: "put example here"

    #------------------------------------------------------------------------
    # POST /activitytypecategories/
    # PUT /activitytypecategories/{ActivityTypeCategoryID}
    # GET /activitytypecategories/{ActivityTypeCategoryID}

    response_body_ActivityTypeCategories_examples:
        value: "put example here"


    #------------------------------------------------------------------------
    # DELETE
    # All resources have a delete that returns this format.
    # XXX: Verify this!

    response_body_delete_examples
        value: "put example here"

  #--------------------------------------------------------------------------
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # XXX: FIXME
